### ISSUE TITLE
Change favicon?

### ISSUE THREAD

**Issue by donkeylobster** [DannyBen/docker-madness#1]
Hi.

What is the best way to update the favicon.ico? 

Now I have this in Dockerfile:
COPY favicon.ico /usr/lib/ruby/gems/2.7.0/gems/madness-0.9.3/app/public/favicon.ico

Can favicon be defined in index.md ?

**Comment by DannyBen** [comment]
You can simply place a file named `favicon.ico` at the root of your madness documentation folder. No need to override the one in the gem.

**Comment by donkeylobster** [comment]
Thanks. This works. 
👍
